services:
  pgdatabase:
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=hwk1
    ports:
      - "5432:9876"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=hwk1@hwk1.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8080:80"
    